trigger:
  branches:
    include:
      - master
  paths:
    include:
      - 'Part 1/java_solution'
      - azure-pipelines-part-1-java.yml

pool:
  vmImage: 'ubuntu-18.04'

container: garyedwardhughes/exchange:latest

variables:
  buildConfiguration: 'Release'

steps:
- script: ant -f Exchange.xml
  workingDirectory: 'Part 1/java_solution'
  displayName: 'Build'
- task: CopyFiles@2
  inputs:
    contents: 'Part 1/java_solution/out/artifacts/Exchange_jar/*'
    targetFolder: $(Build.ArtifactStagingDirectory)
    flattenFolders: true
- task: CopyFiles@2
  inputs:
    contents: 'Part 1/java_solution/runner'
    targetFolder: $(Build.ArtifactStagingDirectory)
    flattenFolders: true
- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: $(Build.ArtifactStagingDirectory)
    artifactName: part_1_java_solution
    publishLocation: 'Container'