# Go
# Build your Go project.
# Add steps that test, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/go

trigger:
  branches:
    include:
      - master
  paths:
    include:
      - 'Part 1/go_solution'
      - azure-pipelines-part-1-go.yml

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    go version
    go get -v -t -d ./...
    go build -v .
  workingDirectory: 'Part 1/go_solution'
  displayName: 'go build'
