trigger:
  branches:
    include:
      - master
  paths:
    include:
      - 'Part 1/swift_solution'
      - azure-pipelines-part-1-swift.yml

pool:
  vmImage: 'ubuntu-18.04'

container: garyedwardhughes/exchange:latest

steps:
- script: 
    swift build -c release
  workingDirectory: 'Part 1/swift_solution'
  displayName: 'swift build'
- task: CopyFiles@2
  inputs:
    contents: 'Part 1/swift_solution/.build/release/Exchange'
    targetFolder: $(Build.ArtifactStagingDirectory)
    flattenFolders: true
- task: CopyFiles@2
  inputs:
    contents: 'Part 1/swift_solution/runner'
    targetFolder: $(Build.ArtifactStagingDirectory)
    flattenFolders: true
- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: $(Build.ArtifactStagingDirectory)
    artifactName: part_1_swift_solution
    publishLocation: 'Container'