trigger:
  branches:
    include:
      - master
  paths:
    include:
      - 'Part 1/csharp_solution'
      - azure-pipelines-part-1-csharp.yml

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet publish --configuration $(buildConfiguration)
  workingDirectory: 'Part 1/csharp_solution'
  displayName: 'dotnet publish $(buildConfiguration)'
- script: dotnet test --configuration $(buildConfiguration)
  workingDirectory: 'Part 1/csharp_solution'
  displayName: 'dotnet test $(buildConfiguration)'
- task: CopyFiles@2
  inputs:
    contents: 'Part 1/csharp_solution/Exchange/bin/Release/netcoreapp3.0/publish/*'
    targetFolder: $(Build.ArtifactStagingDirectory)
- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: $(Build.ArtifactStagingDirectory)
    artifactName: Executable
    publishLocation: 'Container'