# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  branches:
    include:
      - master
  paths:
    include:
      - 'Part 2/fsharp_solution'
      - azure-pipelines-part-2-fsharp.yml

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build --configuration $(buildConfiguration)
  workingDirectory: 'Part 2/fsharp_solution'
  displayName: 'dotnet build $(buildConfiguration)'
- script: dotnet test --configuration $(buildConfiguration)
  workingDirectory: 'Part 2/fsharp_solution'
  displayName: 'dotnet test $(buildConfiguration)'

- task: CopyFiles@2
  inputs:
    contents: 'Part 2/fsharp_solution/Exchange/bin/Release/netcoreapp3.0/publish/*'
    targetFolder: $(Build.ArtifactStagingDirectory)
    flattenFolders: true
- task: CopyFiles@2
  inputs:
    contents: 'Part 2/fsharp_solution/runner'
    targetFolder: $(Build.ArtifactStagingDirectory)
    flattenFolders: true
- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: $(Build.ArtifactStagingDirectory)
    artifactName: part_2_fsharp_solution
    publishLocation: 'Container'