trigger:
  none
  
pool:
  vmImage: 'ubuntu-latest'

steps:
- task: DownloadPipelineArtifact@2
  # Download C++
  inputs:
    buildType: 'specific'
    project: '030b6a1b-1f33-4e57-b63f-f03f0d399d8d'
    definition: '3'
    buildVersionToDownload: 'latest'
    targetPath: '$(Pipeline.Workspace)'
- task: DownloadPipelineArtifact@2
  # Download C#
  inputs:
    buildType: 'specific'
    project: '030b6a1b-1f33-4e57-b63f-f03f0d399d8d'
    definition: '4'
    buildVersionToDownload: 'latest'
    targetPath: '$(Pipeline.Workspace)'
- task: DownloadPipelineArtifact@2
  # Download F#
  inputs:
    buildType: 'specific'
    project: '030b6a1b-1f33-4e57-b63f-f03f0d399d8d'
    definition: '5'
    buildVersionToDownload: 'latest'
    targetPath: '$(Pipeline.Workspace)'
- script: |
    echo "run part 1 benchmarks"
  displayName: 'benchmark'


