trigger:
  none
  
pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self
  clean: true
  persistCredentials: true


- script: |
    ./benchmark.py $(Pipeline.Workspace) part_2 2 orders-100K.txt.gz > part_2_results.md
    git config --global user.email "benchmark@example.com"
    git config --global user.name "benchmark.py"
    git checkout master
    git add part_2_results.md
    git commit -m "updated part 2 results"
    git -c http.extraheader="AUTHORIZATION: bearer $(System.AccessToken)" push
  displayName: 'benchmark'

