trigger:
  branches:
    include:
      - master
  paths:
    include:
      - 'Part 1/go_solution'
      - azure-pipelines-part-1-go.yml

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    go version
    go get -v -t -d ./...
    go build -v .
  workingDirectory: 'Part 1/go_solution'
  displayName: 'go build'

- task: CopyFiles@2
  inputs:
    contents: 'Part 1/go_solution/Exchange'
    targetFolder: $(Build.ArtifactStagingDirectory)
    flattenFolders: true
- task: CopyFiles@2
  inputs:
    contents: 'Part 1/go_solution/runner'
    targetFolder: $(Build.ArtifactStagingDirectory)
    flattenFolders: true
- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: $(Build.ArtifactStagingDirectory)
    artifactName: part_1_go_solution
    publishLocation: 'Container'