trigger:
  branches:
    include:
      - master
  paths:
    include:
      - 'Part 2/go_solution'
      - azure-pipelines-part-2-go.yml

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: go build -v .
  workingDirectory: 'Part 2/go_solution'
  displayName: 'go build'
- task: CopyFiles@2
  inputs:
    contents: 'Part 2/go_solution/geh-exchange-go'
    targetFolder: $(Build.ArtifactStagingDirectory)
    flattenFolders: true
- task: CopyFiles@2
  inputs:
    contents: 'Part 2/go_solution/runner'
    targetFolder: $(Build.ArtifactStagingDirectory)
    flattenFolders: true
- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: $(Build.ArtifactStagingDirectory)
    artifactName: part_2_go_solution
    publishLocation: 'Container'