trigger:
  branches:
    include:
      - master
  paths:
    include:
      - 'Part 2/cpp_solution'
      - azure-pipelines-part-2-cpp.yml

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    sudo apt install -y libboost-all-dev 
    make check
  workingDirectory: 'Part 2/cpp_solution'
  displayName: 'make'
- task: CopyFiles@2
  inputs:
    contents: 'Part 2/cpp_solution/Exchange'
    targetFolder: $(Build.ArtifactStagingDirectory)
- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: $(Build.ArtifactStagingDirectory)
    artifactName: Executable
    publishLocation: 'Container'