trigger:
  branches:
    include:
      - master
  paths:
    include:
      - 'Part 2/csharp_solution'
      - azure-pipelines-part-2-csharp.yml

pool:
  vmImage: 'ubuntu-18.04'

container: garyedwardhughes/exchange:latest

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet publish --configuration $(buildConfiguration)
  workingDirectory: 'Part 2/csharp_solution'
  displayName: 'dotnet publish $(buildConfiguration)'
- script: dotnet test --configuration $(buildConfiguration)
  workingDirectory: 'Part 2/csharp_solution'
  displayName: 'dotnet test $(buildConfiguration)'

- task: CopyFiles@2
  inputs:
    contents: 'Part 2/csharp_solution/Exchange/bin/Release/netcoreapp3.0/publish/*'
    targetFolder: $(Build.ArtifactStagingDirectory)
    flattenFolders: true
- task: CopyFiles@2
  inputs:
    contents: 'Part 2/csharp_solution/runner'
    targetFolder: $(Build.ArtifactStagingDirectory)
    flattenFolders: true
- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: $(Build.ArtifactStagingDirectory)
    artifactName: part_2_csharp_solution
    publishLocation: 'Container'