# C/C++ with GCC
# Build your C/C++ project with GCC using make.
# Add steps that publish test results, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/c-cpp/gcc

trigger:
  branches:
    include:
      - master
  paths:
    include:
      - 'Part 2/cpp_solution'
      - azure-pipelines-part-2-cpp.yml

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    sudo apt install -y libboost-all-dev 
    make check
  workingDirectory: 'Part 2/cpp_solution'
  displayName: 'make'
