#if !canImport(ObjectiveC)
import XCTest

extension ExchangeTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ExchangeTests = [
        ("testDefaultInit", testDefaultInit),
        ("testInsert", testInsert),
        ("testInsertMultiple", testInsertMultiple),
        ("testScenario1", testScenario1),
        ("testScenario2", testScenario2),
        ("testTrade", testTrade),
    ]
}

extension OrderBookTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__OrderBookTests = [
        ("testInit", testInit),
        ("testInsertAsk", testInsertAsk),
        ("testInsertAsksAtDifferentPrices", testInsertAsksAtDifferentPrices),
        ("testInsertAsksAtTheSamePrice", testInsertAsksAtTheSamePrice),
        ("testInsertBid", testInsertBid),
        ("testInsertBidsAtDifferentPrices", testInsertBidsAtDifferentPrices),
        ("testInsertBidsAtTheSamePrice", testInsertBidsAtTheSamePrice),
        ("testMatchAskExactly", testMatchAskExactly),
        ("testMatchAskMultiple", testMatchAskMultiple),
        ("testMatchAskPartial", testMatchAskPartial),
        ("testMatchBidExactly", testMatchBidExactly),
        ("testMatchBidMultiple", testMatchBidMultiple),
        ("testMatchBidPartial", testMatchBidPartial),
        ("testMatchNothing", testMatchNothing),
    ]
}

extension OrderTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__OrderTests = [
        ("testEmptyInit", testEmptyInit),
        ("testInvalidInit", testInvalidInit),
        ("testStringInit", testStringInit),
        ("testWhitespaceInit", testWhitespaceInit),
    ]
}

extension TradeTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__TradeTests = [
        ("testDefaultInit", testDefaultInit),
        ("testToString", testToString),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(ExchangeTests.__allTests__ExchangeTests),
        testCase(OrderBookTests.__allTests__OrderBookTests),
        testCase(OrderTests.__allTests__OrderTests),
        testCase(TradeTests.__allTests__TradeTests),
    ]
}
#endif
