name: Benchmark

on:
  push:
    branches: [ main ]
    paths:
      - 'benchmark.py'
      - 'README_part_1_header.md'
      - 'README_part_2_header.md'
      - 'README-header.md'
  pull_request:
    branches: [ main ]
    paths:
      - 'benchmark.py'
      - 'README_part_1_header.md'
      - 'README_part_2_header.md'
      - 'README-header.md'
  workflow_dispatch:
  
jobs:
  build:

    runs-on: ubuntu-latest
    container: garyedwardhughes/exchange

    steps:
    - uses: actions/checkout@v2

    - name: Download Part 1 C++ Solution
      uses: dawidd6/action-download-artifact@v2
      with:
        github_token: ${{secrets.GITHUB_TOKEN}}
        workflow: part_1_cpp.yml
        name: part_1_cpp
        path: solutions/part_1_cpp

    - name: Download Part 1 C# Solution
      uses: dawidd6/action-download-artifact@v2
      with:
        github_token: ${{secrets.GITHUB_TOKEN}}
        workflow: part_1_csharp.yml
        name: part_1_csharp
        path: solutions/part_1_csharp

    - name: Download Part 1 F# Solution
      uses: dawidd6/action-download-artifact@v2
      with:
        github_token: ${{secrets.GITHUB_TOKEN}}
        workflow: part_1_fsharp.yml
        name: part_1_fsharp
        path: solutions/part_1_fsharp

    - name: Download Part 1 Rust Solution
      uses: dawidd6/action-download-artifact@v2
      with:
        github_token: ${{secrets.GITHUB_TOKEN}}
        workflow: part_1_rust.yml
        name: part_1_rust
        path: solutions/part_1_rust

    - name: Download Part 1 Go Solution
      uses: dawidd6/action-download-artifact@v2
      with:
        github_token: ${{secrets.GITHUB_TOKEN}}
        workflow: part_1_go.yml
        name: part_1_go
        path: solutions/part_1_go

    - name: Download Part 1 Java Solution
      uses: dawidd6/action-download-artifact@v2
      with:
        github_token: ${{secrets.GITHUB_TOKEN}}
        workflow: part_1_java.yml
        name: part_1_java
        path: solutions/part_1_java

    - name: Download Part 1 Python Solution
      uses: dawidd6/action-download-artifact@v2
      with:
        github_token: ${{secrets.GITHUB_TOKEN}}
        workflow: part_1_python.yml
        name: part_1_python
        path: solutions/part_1_python    
        
    - name: Download Part 1 Cython Solution
      uses: dawidd6/action-download-artifact@v2
      with:
        github_token: ${{secrets.GITHUB_TOKEN}}
        workflow: part_1_cython.yml
        name: part_1_cython
        path: solutions/part_1_cython    
  
    - name: Download Part 1 C Solution
      uses: dawidd6/action-download-artifact@v2
      with:
        github_token: ${{secrets.GITHUB_TOKEN}}
        workflow: part_1_c.yml
        name: part_1_c
        path: solutions/part_1_c    
 
    - name: Download Part 1 Swift Solution
      uses: dawidd6/action-download-artifact@v2
      with:
        github_token: ${{secrets.GITHUB_TOKEN}}
        workflow: part_1_swift.yml
        name: part_1_swift
        path: solutions/part_1_swift    
 
    - name: Download Part 1 TypeScript Solution
      uses: dawidd6/action-download-artifact@v2
      with:
        github_token: ${{secrets.GITHUB_TOKEN}}
        workflow: part_1_typescript.yml
        name: part_1_typescript
        path: solutions/part_1_typescript    

    - name: Download Part 2 C++ Solution
      uses: dawidd6/action-download-artifact@v2
      with:
        github_token: ${{secrets.GITHUB_TOKEN}}
        workflow: part_2_cpp.yml
        name: part_2_cpp
        path: solutions/part_2_cpp

    - name: Download Part 2 C# Solution
      uses: dawidd6/action-download-artifact@v2
      with:
        github_token: ${{secrets.GITHUB_TOKEN}}
        workflow: part_2_csharp.yml
        name: part_2_csharp
        path: solutions/part_2_csharp

    - name: Download Part 2 F# Solution
      uses: dawidd6/action-download-artifact@v2
      with:
        github_token: ${{secrets.GITHUB_TOKEN}}
        workflow: part_2_fsharp.yml
        name: part_2_fsharp
        path: solutions/part_2_fsharp

    - name: Download Part 2 Rust Solution
      uses: dawidd6/action-download-artifact@v2
      with:
        github_token: ${{secrets.GITHUB_TOKEN}}
        workflow: part_2_rust.yml
        name: part_2_rust
        path: solutions/part_2_rust

    - name: Download Part 2 Go Solution
      uses: dawidd6/action-download-artifact@v2
      with:
        github_token: ${{secrets.GITHUB_TOKEN}}
        workflow: part_2_go.yml
        name: part_2_go
        path: solutions/part_2_go

    - name: Download Part 2 Java Solution
      uses: dawidd6/action-download-artifact@v2
      with:
        github_token: ${{secrets.GITHUB_TOKEN}}
        workflow: part_2_java.yml
        name: part_2_java
        path: solutions/part_2_java

    - name: Download Part 2 Python Solution
      uses: dawidd6/action-download-artifact@v2
      with:
        github_token: ${{secrets.GITHUB_TOKEN}}
        workflow: part_2_python.yml
        name: part_2_python
        path: solutions/part_2_python    
        
    - name: Download Part 2 Cython Solution
      uses: dawidd6/action-download-artifact@v2
      with:
        github_token: ${{secrets.GITHUB_TOKEN}}
        workflow: part_2_cython.yml
        name: part_2_cython
        path: solutions/part_2_cython    
  
    - name: Download Part 2 C Solution
      uses: dawidd6/action-download-artifact@v2
      with:
        github_token: ${{secrets.GITHUB_TOKEN}}
        workflow: part_2_c.yml
        name: part_2_c
        path: solutions/part_2_c    
 
    - name: Download Part 2 Swift Solution
      uses: dawidd6/action-download-artifact@v2
      with:
        github_token: ${{secrets.GITHUB_TOKEN}}
        workflow: part_2_swift.yml
        name: part_2_swift
        path: solutions/part_2_swift   

    - name: Download Part 2 TypeScript Solution
      uses: dawidd6/action-download-artifact@v2
      with:
        github_token: ${{secrets.GITHUB_TOKEN}}
        workflow: part_2_typescript.yml
        name: part_2_typescript
        path: solutions/part_2_typescript   
  
    - name: Run Part 1 Benchmark
      run: |
        ./benchmark.py solutions part_1 1 orders-100K.txt.gz > part_1_results.md
        
    - name: Run Part 2 Benchmark
      run: |
        ./benchmark.py solutions part_2 5 orders-100K.txt.gz orders-10M.txt.gz > part_2_results.md
   
    - name: Generate README.md
      run: ./generate_README.sh
      
    - name: Commit README.md
      uses: EndBug/add-and-commit@v4
      with:
        author_name: benchmark.py
        author_email: benchmark@example.com
        message: "Update benchmark results"
        add: "part_1_results.md part_2_results.md README.md"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
