name: Benchmark

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Download Part 1 C++ Solution
      uses: dawidd6/action-download-artifact@v2
      with:
        github_token: ${{secrets.GITHUB_TOKEN}}
        workflow: part_1_cpp.yml
        commit: d64f7bdee31ea6bc9b571395454f90cf861a3115
        name: part_1_cpp
        path: solutions/part_1_cpp

    - name: Download Part 1 C# Solution
      uses: dawidd6/action-download-artifact@v2
      with:
        github_token: ${{secrets.GITHUB_TOKEN}}
        workflow: part_1_csharp.yml
        commit: 21c857269ce71e0cc99b24fe39c1a6ec2c3be65e
        name: part_1_csharp
        path: solutions/part_1_csharp

    - name: Download Part 1 F# Solution
      uses: dawidd6/action-download-artifact@v2
      with:
        github_token: ${{secrets.GITHUB_TOKEN}}
        workflow: part_1_fsharp.yml
        commit: 4cacc065653a9d403b24ea9332564ce1323392b1
        name: part_1_fsharp
        path: solutions/part_1_fsharp

    - name: Download Part 1 Rust Solution
      uses: dawidd6/action-download-artifact@v2
      with:
        github_token: ${{secrets.GITHUB_TOKEN}}
        workflow: part_1_rust.yml
        commit: e8b0caeb41c9eb87244341b13b73e1f269eb8bf3
        name: part_1_rust
        path: solutions/part_1_rust

    - name: Download Part 1 Go Solution
      uses: dawidd6/action-download-artifact@v2
      with:
        github_token: ${{secrets.GITHUB_TOKEN}}
        workflow: part_1_go.yml
        commit: 1975384b5fbb1b3dc7d95cae7db12d306d86c519
        name: part_1_go
        path: solutions/part_1_go

    - name: Download Part 1 Java Solution
      uses: dawidd6/action-download-artifact@v2
      with:
        github_token: ${{secrets.GITHUB_TOKEN}}
        workflow: part_1_java.yml
        commit: 29855509dbd92814b166f711a9185ebe1d528026 
        name: part_1_java
        path: solutions/part_1_java

    - name: Download Part 1 Python Solution
      uses: dawidd6/action-download-artifact@v2
      with:
        github_token: ${{secrets.GITHUB_TOKEN}}
        workflow: part_1_python.yml
        commit: 5a46819c3e7e340203bbf7227d15b9ef9b6debae
        name: part_1_python
        path: solutions/part_1_python    
        
    - name: Download Part 1 Cython Solution
      uses: dawidd6/action-download-artifact@v2
      with:
        github_token: ${{secrets.GITHUB_TOKEN}}
        workflow: part_1_cython.yml
        commit: 6c6ca3b4a62045f69bf8da1031b0bbc00ac9607b
        name: part_1_cython
        path: solutions/part_1_cython    
  
    - name: Download Part 1 C Solution
      uses: dawidd6/action-download-artifact@v2
      with:
        github_token: ${{secrets.GITHUB_TOKEN}}
        workflow: part_1_c.yml
        commit: e5874c309cd4ce493d3f27e523d9eb6cc65a8d70
        name: part_1_c
        path: solutions/part_1_c    
 
    - name: Download Part 1 Swift Solution
      uses: dawidd6/action-download-artifact@v2
      with:
        github_token: ${{secrets.GITHUB_TOKEN}}
        workflow: part_1_swift.yml
        commit: 6b0a56c3101b0edb5cbc0d20602c32a2b66fad1f
        name: part_1_swift
        path: solutions/part_1_swift    
 
  
    - name: Display structure of downloaded files
      run: ls -R
