name: Benchmark

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2


    - name: Download Part 1 C++ Solution
      uses: dawidd6/action-download-artifact@v2
      with:
        github_token: ${{secrets.GITHUB_TOKEN}}
        workflow: part_1_cpp.yml
        commit: d64f7bdee31ea6bc9b571395454f90cf861a3115
        name: part_1_cpp
        path: part_1_solutions
 
    - name: Display structure of downloaded files
      run: ls -R
