name: Benchmark

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  COMMIT: f1716cf5b0ff217fcb3bd3454224ccbeb8926722

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Download Part 1 C++ Solution
      uses: dawidd6/action-download-artifact@v2
      with:
        github_token: ${{secrets.GITHUB_TOKEN}}
        workflow: part_1_cpp.yml
        commit: ${{ env.COMMIT }}
        name: part_1_cpp
        path: solutions/part_1_cpp

    - name: Download Part 1 C# Solution
      uses: dawidd6/action-download-artifact@v2
      with:
        github_token: ${{secrets.GITHUB_TOKEN}}
        workflow: part_1_csharp.yml
        commit: ${{ env.COMMIT }}
        name: part_1_csharp
        path: solutions/part_1_csharp

    - name: Download Part 1 F# Solution
      uses: dawidd6/action-download-artifact@v2
      with:
        github_token: ${{secrets.GITHUB_TOKEN}}
        workflow: part_1_fsharp.yml
        commit: ${{ env.COMMIT }}
        name: part_1_fsharp
        path: solutions/part_1_fsharp

    - name: Download Part 1 Rust Solution
      uses: dawidd6/action-download-artifact@v2
      with:
        github_token: ${{secrets.GITHUB_TOKEN}}
        workflow: part_1_rust.yml
        commit: ${{ env.COMMIT }}
        name: part_1_rust
        path: solutions/part_1_rust

    - name: Download Part 1 Go Solution
      uses: dawidd6/action-download-artifact@v2
      with:
        github_token: ${{secrets.GITHUB_TOKEN}}
        workflow: part_1_go.yml
        commit: ${{ env.COMMIT }}
        name: part_1_go
        path: solutions/part_1_go

    - name: Download Part 1 Java Solution
      uses: dawidd6/action-download-artifact@v2
      with:
        github_token: ${{secrets.GITHUB_TOKEN}}
        workflow: part_1_java.yml
        commit: ${{ env.COMMIT }}
        name: part_1_java
        path: solutions/part_1_java

    - name: Download Part 1 Python Solution
      uses: dawidd6/action-download-artifact@v2
      with:
        github_token: ${{secrets.GITHUB_TOKEN}}
        workflow: part_1_python.yml
        commit: ${{ env.COMMIT }}
        name: part_1_python
        path: solutions/part_1_python    
        
    - name: Download Part 1 Cython Solution
      uses: dawidd6/action-download-artifact@v2
      with:
        github_token: ${{secrets.GITHUB_TOKEN}}
        workflow: part_1_cython.yml
        commit: ${{ env.COMMIT }}
        name: part_1_cython
        path: solutions/part_1_cython    
  
    - name: Download Part 1 C Solution
      uses: dawidd6/action-download-artifact@v2
      with:
        github_token: ${{secrets.GITHUB_TOKEN}}
        workflow: part_1_c.yml
        commit: ${{ env.COMMIT }}
        name: part_1_c
        path: solutions/part_1_c    
 
    - name: Download Part 1 Swift Solution
      uses: dawidd6/action-download-artifact@v2
      with:
        github_token: ${{secrets.GITHUB_TOKEN}}
        workflow: part_1_swift.yml
        commit: ${{ env.COMMIT }}
        name: part_1_swift
        path: solutions/part_1_swift    
 
    - name: Download Part 2 C++ Solution
      uses: dawidd6/action-download-artifact@v2
      with:
        github_token: ${{secrets.GITHUB_TOKEN}}
        workflow: part_2_cpp.yml
        commit: ${{ env.COMMIT }}
        name: part_2_cpp
        path: solutions/part_2_cpp

    - name: Download Part 2 C# Solution
      uses: dawidd6/action-download-artifact@v2
      with:
        github_token: ${{secrets.GITHUB_TOKEN}}
        workflow: part_2_csharp.yml
        commit: ${{ env.COMMIT }}
        name: part_2_csharp
        path: solutions/part_2_csharp

    - name: Download Part 2 F# Solution
      uses: dawidd6/action-download-artifact@v2
      with:
        github_token: ${{secrets.GITHUB_TOKEN}}
        workflow: part_2_fsharp.yml
        commit: ${{ env.COMMIT }}
        name: part_2_fsharp
        path: solutions/part_2_fsharp

    - name: Download Part 2 Rust Solution
      uses: dawidd6/action-download-artifact@v2
      with:
        github_token: ${{secrets.GITHUB_TOKEN}}
        workflow: part_2_rust.yml
        commit: ${{ env.COMMIT }}
        name: part_2_rust
        path: solutions/part_2_rust

    - name: Download Part 2 Go Solution
      uses: dawidd6/action-download-artifact@v2
      with:
        github_token: ${{secrets.GITHUB_TOKEN}}
        workflow: part_2_go.yml
        commit: ${{ env.COMMIT }}
        name: part_2_go
        path: solutions/part_2_go

    - name: Download Part 2 Java Solution
      uses: dawidd6/action-download-artifact@v2
      with:
        github_token: ${{secrets.GITHUB_TOKEN}}
        workflow: part_2_java.yml
        commit: ${{ env.COMMIT }}
        name: part_2_java
        path: solutions/part_2_java

    - name: Download Part 2 Python Solution
      uses: dawidd6/action-download-artifact@v2
      with:
        github_token: ${{secrets.GITHUB_TOKEN}}
        workflow: part_2_python.yml
        commit: ${{ env.COMMIT }}
        name: part_2_python
        path: solutions/part_2_python    
        
    - name: Download Part 2 Cython Solution
      uses: dawidd6/action-download-artifact@v2
      with:
        github_token: ${{secrets.GITHUB_TOKEN}}
        workflow: part_2_cython.yml
        commit: ${{ env.COMMIT }}
        name: part_2_cython
        path: solutions/part_2_cython    
  
    - name: Download Part 2 C Solution
      uses: dawidd6/action-download-artifact@v2
      with:
        github_token: ${{secrets.GITHUB_TOKEN}}
        workflow: part_2_c.yml
        commit: ${{ env.COMMIT }}
        name: part_2_c
        path: solutions/part_2_c    
 
    - name: Download Part 2 Swift Solution
      uses: dawidd6/action-download-artifact@v2
      with:
        github_token: ${{secrets.GITHUB_TOKEN}}
        workflow: part_2_swift.yml
        commit: ${{ env.COMMIT }}
        name: part_2_swift
        path: solutions/part_2_swift    
  
    - name: Display structure of downloaded files
      run: ls -R
