name: Part 2 - TypeScript

on:
  push:
    branches: [ main ]
    paths:
      - 'part_2/typescript_solution/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'part_2/typescript_solution/**'
  workflow_dispatch:
     
jobs:
  build:

    runs-on: ubuntu-latest
    container: garyedwardhughes/exchange

    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: build
      working-directory: './part_2/typescript_solution'
      run: npm install && npm run build
    - name: upload Exchange
      uses: actions/upload-artifact@v2
      with:
        name: part_2_typescript	
        path: ./part_2/typescript_solution/build 
    - name: upload runner
      uses: actions/upload-artifact@v2
      with:
        name: part_2_typescript
        path: ./part_2/typescript_solution/runner
