name: Part 2 - Python

on:
  push:
    branches: [ main ]
    paths:
      - 'part_2/python_solution/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'part_2/python_solution/**'
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    container: garyedwardhughes/exchange

    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: build
      working-directory: './part_2/python_solution'
      run: python3 -m py_compile *.py
    - name: upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: part_2_python	
        path: |
          ./part_2/python_solution/*.py 
          ./part_2/python_solution/runner 
        overwrite: true