name: Part 1 - C

on:
  push:
    branches: [ main ]
    paths:
      - 'part_1/c_solution/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'part_1/c_solution/**'
  workflow_dispatch:
    
jobs:
  build:

    runs-on: ubuntu-latest
    container: garyedwardhughes/exchange

    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: make
      working-directory: './part_1/c_solution'
      run: make
    - name: make check
      working-directory: './part_1/c_solution'
      run: make check
    - name: upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: part_1_c	
        path: |
          ./part_1/c_solution/Exchange
          ./part_1/c_solution/runner
        overwrite: true
