name: Part 2 - Swift

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:
  build:

    runs-on: ubuntu-18.04
    container: garyedwardhughes/exchange

    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: setup path
      run: ln -s 'Part 2' part_2
    - name: build
      working-directory: './part_2/swift_solution'
      run: swift build -c release
    - name: upload Exchange
      uses: actions/upload-artifact@v2
      with:
        name: part_2_swift	
        path: ./part_2/swift_solution/.build/release/Exchange
    - name: upload runner
      uses: actions/upload-artifact@v2
      with:
        name: part_2_swift	
        path: ./part_2/swift_solution/runner 
