name: Part 1 - F#

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:
  build:

    runs-on: ubuntu-18.04
    container: garyedwardhughes/exchange

    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: setup path
      run: ln -s 'Part 1' part_1
    - name: build
      working-directory: './part_1/fsharp_solution'
      run: dotnet publish --configuration Release
    - name: test
      working-directory: './part_1/fsharp_solution'
      run: dotnet test --configuration Release
    - name: upload Exchange
      uses: actions/upload-artifact@v2
      with:
        name: part_1_fsharp	
        path: ./part_1/fsharp_solution/Exchange/bin/Release/netcoreapp3.0/publish/* 
    - name: upload runner
      uses: actions/upload-artifact@v2
      with:
        name: part_1_fsharp	
        path: ./part_1/fsharp_solution/runner 
