name: Part 1 - F#

on:
  push:
    branches: [ main ]
    paths:
      - 'part_1/fsharp_solution/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'part_1/fsharp_solution/**'
  workflow_dispatch:
     
jobs:
  build:

    runs-on: ubuntu-latest
    container: garyedwardhughes/exchange

    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: build
      working-directory: './part_1/fsharp_solution'
      run: dotnet publish --configuration Release
    - name: test
      working-directory: './part_1/fsharp_solution'
      run: dotnet test --configuration Release
    - name: upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: part_1_fsharp	
        path: |
          ./part_1/fsharp_solution/Exchange/bin/Release/net9.0/publish/*
          ./part_1/fsharp_solution/runner 
        overwrite: true