name: Part 1 - Go

on:
  push:
    branches: [ main ]
    paths:
      - 'part_1/go_solution/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'part_1/go_solution/**'
  workflow_dispatch:
    
jobs:
  build:

    runs-on: ubuntu-latest
    container: garyedwardhughes/exchange

    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: build
      working-directory: './part_1/go_solution'
      run: |
        git config --global safe.directory '*'
        go version
        go get -v -t -d ./...
        go build -v .
    - name: upload Exchange
      uses: actions/upload-artifact@v4
      with:
        name: part_1_go
        path: ./part_1/go_solution/Exchange 
    - name: upload runner
      uses: actions/upload-artifact@v4
      with:
        name: part_1_go	
        path: ./part_1/go_solution/runner 
