name: Part 1 - Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:
  build:

    runs-on: ubuntu-18.04
    container: garyedwardhughes/exchange

    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: setup path
      run: ln -s 'Part 1' part_1
    - name: build
      working-directory: './part_1/go_solution'
      run: |
        go version
        go get -v -t -d ./...
        go build -v .
    - name: upload Exchange
      uses: actions/upload-artifact@v2
      with:
        name: part_1_go
        path: ./part_1/go_solution/Exchange 
    - name: upload runner
      uses: actions/upload-artifact@v2
      with:
        name: part_1_go	
        path: ./part_1/go_solution/runner 
