name: Part 1 - C#

on:
  push:
    branches: [ main ]
    paths:
      - 'part_1/csharp_solution/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'part_1/csharp_solution/**'
    
jobs:
  build:

    runs-on: ubuntu-18.04
    container: garyedwardhughes/exchange

    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: build
      working-directory: './part_1/csharp_solution'
      run: dotnet publish --configuration Release
    - name: test
      working-directory: './part_1/csharp_solution'
      run: dotnet test --configuration Release
    - name: upload Exchange
      uses: actions/upload-artifact@v2
      with:
        name: part_1_csharp	
        path: ./part_1/csharp_solution/Exchange/bin/Release/netcoreapp3.0/publish/* 
    - name: upload runner
      uses: actions/upload-artifact@v2
      with:
        name: part_1_csharp	
        path: ./part_1/csharp_solution/runner 
