name: Part 1 - TypeScript

on:
  push:
    branches: [ main ]
    paths:
      - 'part_1/typescript_solution/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'part_1/typescript_solution/**'
  workflow_dispatch:
    
jobs:
  build:

    runs-on: ubuntu-latest
    container: garyedwardhughes/exchange

    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: build
      working-directory: './part_1/typescript_solution'
      run: npm install && npm run build
    - name: upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: part_1_typescript	
        path: |
          ./part_1/typescript_solution/build 
          ./part_1/typescript_solution/runner
        overwrite: true