name: Part 2 - Swift

on:
  push:
    branches: [ main ]
    paths:
      - 'part_2/swift_solution/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'part_2/swift_solution/**'
  workflow_dispatch:
     
jobs:
  build:

    runs-on: ubuntu-latest
    container: garyedwardhughes/exchange

    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: build
      working-directory: './part_2/swift_solution'
      run: |
        swift build -c release
        cp .build/release/Exchange .
    - name: upload Exchange
      uses: actions/upload-artifact@v4
      with:
        name: part_2_swift	
        path: './part_2/swift_solution/Exchange'
        overwrite: true
    - name: upload runner
      uses: actions/upload-artifact@v4
      with:
        name: part_2_swift	
        path: ./part_2/swift_solution/runner 
        overwrite: true
