name: Part 2 - C++

on:
  push:
    branches: [ master ]
    paths: 'Part 2/cpp_solution'
  pull_request:
    branches: [ master ]
    paths: 'Part 2/cpp_solution'
    
jobs:
  build:

    runs-on: ubuntu-18.04
    container: garyedwardhughes/exchange

    steps:
    - uses: actions/checkout@v2
    - name: setup path
      run: ln -s 'Part 2' part_2
    - name: make
      working-directory: './part_2/cpp_solution'
      run: make
    - name: make check
      working-directory: './part_2/cpp_solution'
      run: make check
   
