name: Part 1 - Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:
  build:

    runs-on: ubuntu-18.04
    container: garyedwardhughes/exchange

    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: setup path
      run: ln -s 'Part 1' part_1
    - name: install
      working-directory: './part_1/rust_solution'
      run: |
        curl https://sh.rustup.rs -sSf | sh -s -- -y
    - name: build
      run: source $HOME/.cargo/env && cargo build --release
    - name: test
      working-directory: './part_1/csharp_solution'
      run: source $HOME/.cargo/env && cargo test --all
    - name: upload Exchange
      uses: actions/upload-artifact@v2
      with:
        name: part_1_rust	
        path: ./part_1/rust_solution/exchange 
    - name: upload runner
      uses: actions/upload-artifact@v2
      with:
        name: part_1_rust	
        path: ./part_1/rust_solution/runner 
