name: Part 2 - C++

on:
  push:
    branches: [ main ]
    paths:
      - 'part_2/cpp_solution'
    pull_request:
    branches: [ main ]
    paths:
      - 'part_2/cpp_solution'
    
jobs:
  build:

    runs-on: ubuntu-18.04
    container: garyedwardhughes/exchange

    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: make
      working-directory: './part_2/cpp_solution'
      run: make
    - name: make check
      working-directory: './part_2/cpp_solution'
      run: make check
    - name: upload Exchange
      uses: actions/upload-artifact@v2
      with:
        name: part_2_cpp	
        path: ./part_2/cpp_solution/Exchange 
    - name: upload runner
      uses: actions/upload-artifact@v2
      with:
        name: part_2_cpp	
        path: ./part_2/cpp_solution/runner 
  
        
    
    
   
   
