name: Part 2 - C++

on:
  push:
    branches: [ master ]
    paths:
    - 'Part 2/cpp_solution'
   
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make
    - name: make check
      run: make check


