name: Part 2 - Java

on:
  push:
    branches: [ main ]
    paths:
      - 'part_2/java_solution/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'part_2/java_solution/**'
  workflow_dispatch:
     
jobs:
  build:

    runs-on: ubuntu-latest
    container: garyedwardhughes/exchange

    steps:
    - name: checkout
      uses: actions/checkout@v7
    - name: build
      working-directory: './part_2/java_solution'
      run: ant -f Exchange.xml
    - name: copy runner into build output
      working-directory: './part_2/java_solution'
      run: cp runner out/artifacts/Exchange_jar/runner
    - name: upload artifacts
      uses: actions/upload-artifact@v7
      with:
        name: part_2_java
        path: ./part_2/java_solution/out/artifacts/Exchange_jar
        overwrite: true