name: Part 1 - Rust

on:
  push:
    branches: [ main ]
    paths:
      - 'part_1/rust_solution'
    pull_request:
    branches: [ main ]
    paths:
      - 'part_1/rust_solution'
    
jobs:
  build:

    runs-on: ubuntu-18.04
    container: garyedwardhughes/exchange

    steps:
    - name: checkout
      uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - name: build
      working-directory: './part_1/rust_solution'
      run: cargo build --release
    - name: test
      working-directory: './part_1/rust_solution'
      run: cargo test --all
    - name: upload Exchange
      uses: actions/upload-artifact@v2
      with:
        name: part_1_rust	
        path: ./part_1/rust_solution/target/release/exchange 
    - name: upload runner
      uses: actions/upload-artifact@v2
      with:
        name: part_1_rust	
        path: ./part_1/rust_solution/runner 
