name: Part 1 - C++

on:
  push:
    branches: [ master ]
    paths:
    - 'Part 1/cpp_solution'
 
jobs:
  build:
    runs-on: ubuntu-latest
    container: garyedwardhughes/exchange
    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make
    - name: make check
      run: make check
