name: Part 1 - Java

on:
  push:
    branches: [ main ]
    paths:
      - 'part_1/java_solution/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'part_1/java_solution/**'
  workflow_dispatch:
     
jobs:
  build:

    runs-on: ubuntu-latest
    container: garyedwardhughes/exchange

    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: build
      working-directory: './part_1/java_solution'
      run: ant -f Exchange.xml
    - name: upload Exchange
      uses: actions/upload-artifact@v2
      with:
        name: part_1_java	
        path: ./part_1/java_solution/out/artifacts/Exchange_jar/* 
    - name: upload runner
      uses: actions/upload-artifact@v2
      with:
        name: part_1_java	
        path: ./part_1/java_solution/runner 
