name: Part 2 - Cython

on:
  push:
    branches: [ master ]
    paths:
      - 'part_2/cython_solution'
  pull_request:
    branches: [ master ]
    paths:
      - 'part_2/cython_solution'
    
jobs:
  build:

    runs-on: ubuntu-18.04
    container: garyedwardhughes/exchange

    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: build
      working-directory: './part_2/cython_solution'
      run: python3 setup.py build_ext --inplace
    - name: upload Exchange
      uses: actions/upload-artifact@v2
      with:
        name: part_2_cython	
        path: ./part_2/cython_solution/Exchange.so
    - name: upload runner
      uses: actions/upload-artifact@v2
      with:
        name: part_2_cython	
        path: ./part_2/cython_solution/runner 
