name: Part 1 - Rust

on:
  push:
    branches: [ main ]
    paths:
      - 'part_1/rust_solution/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'part_1/rust_solution/**'
  workflow_dispatch:

jobs:
  build:
  
    runs-on: ubuntu-latest
    container: garyedwardhughes/exchange

    steps:
    - name: checkout
      uses: actions/checkout@v4
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - name: build
      working-directory: './part_1/rust_solution'
      run: cargo build --release
    - name: test
      working-directory: './part_1/rust_solution'
      run: cargo test --all
    - name: upload Exchange
      uses: actions/upload-artifact@v4
      with:
        name: part_1_rust	
        path: |
          ./part_1/rust_solution/target/release/exchange
          ./part_1/rust_solution/runner 
        overwrite: true