name: Part 2 - C++

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
defaults:
  run:
    working-directory: 'Part 2/cpp_solution'
    
jobs:
  build:

    runs-on: ubuntu-18.04
    container: garyedwardhughes/exchange

    steps:
    - uses: actions/checkout@v2
    - name: setup path
      run: ln -s 'Part 2' part_2
    - name: make
      run: make
    - name: make check
      run: make check
   
