name: Part 2 - C++

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-18.04
    container: garyedwardhughes/exchange

    steps:
    - uses: actions/checkout@v2
    - working-directory: 'Part 1/cpp_solution'
    - name: make
      run: make
    - name: make check
      run: make check
   
