name: Part 2 - Java

on:
  push:
    branches: [ main ]
    paths:
      - 'part_2/java_solution/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'part_2/java_solution/**'
    
jobs:
  build:

    runs-on: ubuntu-18.04
    container: garyedwardhughes/exchange

    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: build
      working-directory: './part_2/java_solution'
      run: ant -f Exchange.xml
    - name: upload Exchange
      uses: actions/upload-artifact@v2
      with:
        name: part_2_java	
        path: ./part_2/java_solution/out/artifacts/Exchange_jar/* 
    - name: upload runner
      uses: actions/upload-artifact@v2
      with:
        name: part_2_java	
        path: ./part_2/java_solution/runner 
