name: Part 2 - Go

on:
  push:
    branches: [ main ]
    paths:
      - 'part_2/go_solution/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'part_2/go_solution/**'
    
jobs:
  build:

    runs-on: ubuntu-18.04
    container: garyedwardhughes/exchange

    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: build
      working-directory: './part_2/go_solution'
      run: |
        go version
        go get -v -t -d ./...
        go build -v .
    - name: upload Exchange
      uses: actions/upload-artifact@v2
      with:
        name: part_2_go
        path: ./part_2/go_solution/Exchange 
    - name: upload runner
      uses: actions/upload-artifact@v2
      with:
        name: part_2_go	
        path: ./part_2/go_solution/runner 
