name: Part 2 - Go

on:
  push:
    branches: [ main ]
    paths:
      - 'part_2/go_solution/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'part_2/go_solution/**'
  workflow_dispatch:
     
jobs:
  build:

    runs-on: ubuntu-latest
    container: garyedwardhughes/exchange

    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: build
      working-directory: './part_2/go_solution'
      run: |
        git config --global safe.directory '*'
        go version
        go get -v -t -d ./...
        go build -v .
    - name: upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: part_2_go
        path: |
          ./part_2/go_solution/Exchange 
          ./part_2/go_solution/runner 
        overwrite: true