name: Part 2 - F#

on:
  push:
    branches: [ main ]
    paths:
      - 'part_2/fsharp_solution/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'part_2/fsharp_solution/**'
  workflow_dispatch:
     
jobs:
  build:

    runs-on: ubuntu-latest
    container: garyedwardhughes/exchange

    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: build
      working-directory: './part_2/fsharp_solution'
      run: dotnet publish --configuration Release
    - name: test
      working-directory: './part_2/fsharp_solution'
      run: dotnet test --configuration Release
    - name: upload Exchange
      uses: actions/upload-artifact@v4
      with:
        name: part_2_fsharp	
        path: ./part_2/fsharp_solution/Exchange/bin/Release/net8.0/publish/* 
        overwrite: true
    - name: upload runner
      uses: actions/upload-artifact@v4
      with:
        name: part_2_fsharp	
        path: ./part_2/fsharp_solution/runner 
        overwrite: true
